// frontend/components/AICoach/AnalysisCard.jsx

import React from 'react';
import { TrendingUp, Target, Award, AlertCircle } from 'lucide-react';


const AnalysisCard = ({ analysis }) => {
  if (!analysis || !analysis.success) {
    return null;
  }

  return (
    <div className="bg-gradient-to-br from-blue-900 to-purple-900 rounded-xl p-6 text-white shadow-xl">
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <Award className="text-yellow-400" size={32} />
        <div>
          <h2 className="text-2xl font-bold">AI Coach Analysis</h2>
          <p className="text-blue-200 text-sm">Personalized improvement recommendations</p>
        </div>
      </div>

      {/* Overall Assessment */}
      <div className="bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-6 border border-white/20">
        <div className="flex items-start gap-3">
          <TrendingUp className="text-green-400 flex-shrink-0 mt-1" size={24} />
          <div>
            <h3 className="font-bold text-lg mb-1">Overall Assessment</h3>
            <p className="text-blue-100">{analysis.overall_assessment}</p>
          </div>
        </div>
      </div>

      {/* Priority Advice */}
      <div className="space-y-4">
        <h3 className="text-xl font-bold flex items-center gap-2 mb-3">
          <Target className="text-yellow-400" size={24} />
          Top 3 Areas to Improve
        </h3>
        
        {analysis.advice && analysis.advice.map((item, idx) => (
          <div 
            key={idx} 
            className="bg-white/10 backdrop-blur-sm rounded-lg p-4 border border-white/20 hover:border-blue-400/50 transition-all"
          >
            <div className="flex items-start gap-3">
              <div className="bg-blue-500 text-white rounded-full w-8 h-8 flex items-center justify-center font-bold flex-shrink-0">
                {item.priority}
              </div>
              <div className="flex-1">
                <h4 className="font-bold text-lg mb-2">{item.title}</h4>
                <p className="text-blue-100 text-sm mb-3">{item.advice}</p>
                
                {/* Gap Info */}
                {item.gap_info && (
                  <div className="bg-slate-900/50 rounded px-3 py-2 mb-3 text-sm">
                    <div className="flex justify-between">
                      <span className="text-blue-300">Your stat: <strong>{item.gap_info.player_value}</strong></span>
                      <span className="text-green-300">Target: <strong>{item.gap_info.target_value}</strong></span>
                    </div>
                  </div>
                )}

                {/* Training Drills */}
                {item.drills && item.drills.length > 0 && (
                  <div className="mt-2">
                    <p className="text-xs text-blue-300 font-semibold mb-1">Recommended Training:</p>
                    <div className="flex flex-wrap gap-2">
                      {item.drills.map((drill, dIdx) => (
                        <span 
                          key={dIdx}
                          className="bg-blue-600/30 text-blue-200 text-xs px-2 py-1 rounded"
                        >
                          {drill}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Stats Summary */}
      {analysis.all_gaps && analysis.all_gaps.length > 0 && (
        <div className="mt-6 bg-white/5 rounded-lg p-4 border border-white/10">
          <h4 className="font-bold mb-3 flex items-center gap-2">
            <AlertCircle size={18} className="text-yellow-400" />
            All Stats vs Next Rank
          </h4>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
            {analysis.all_gaps.slice(0, 6).map((gap, idx) => (
              <div key={idx} className="bg-slate-900/30 rounded p-2 text-sm">
                <div className="text-blue-300 text-xs capitalize mb-1">
                  {gap.stat.replace(/_/g, ' ')}
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-white font-semibold">{gap.player_value}</span>
                  <span className={`text-xs font-bold ${gap.gap > 0 ? 'text-red-400' : 'text-green-400'}`}>
                    {gap.gap > 0 ? '↓' : '↑'} {Math.abs(gap.gap_percentage).toFixed(0)}%
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default AnalysisCard;

// frontend/src/app/analysis-card/analysis-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-analysis-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './analysis-card.component.html',
  styleUrls: ['./analysis-card.component.css']
})
export class AnalysisCardComponent {
  @Input() analysis: any;

  formatStatName(stat: string): string {
    return stat.replace(/_/g, ' ');
  }
}

<div *ngIf="analysis?.success" class="card" style="background: linear-gradient(to right, #0f172a, #1e3a8a);">
  <div style="display:flex; align-items:center; gap:12px; margin-bottom:16px;">
    <span style="font-size:1.5rem; color:#fbbf24;">🏆</span>
    <div>
      <h2 style="margin:0; font-size:1.6rem;">AI Coach Analysis</h2>
      <p style="margin:4px 0 0; color:#cbd5e1;">Personalized improvement recommendations</p>
    </div>
  </div>

  <div class="card" style="background: rgba(255,255,255,0.08); padding:16px; margin-bottom:16px; border:1px solid rgba(255,255,255,0.12);">
    <h3 style="margin:0 0 8px;">Overall Assessment</h3>
    <p style="margin:0; color:#e2e8f0;">{{ analysis.overall_assessment }}</p>
  </div>

  <div *ngIf="analysis.advice?.length">
    <h3 style="margin-top:0;">Top 3 Areas to Improve</h3>
    <div *ngFor="let item of analysis.advice" style="margin-bottom:16px; padding:16px; background: rgba(255,255,255,0.05); border:1px solid rgba(255,255,255,0.12); border-radius:12px;">
      <div style="display:flex; align-items:flex-start; gap:12px; margin-bottom:8px;">
        <div style="width:32px; height:32px; border-radius:50%; background:#3b82f6; display:flex; align-items:center; justify-content:center; font-weight:700;">{{ item.priority }}</div>
        <div>
          <h4 style="margin:0 0 4px;">{{ item.title }}</h4>
          <p style="margin:0; color:#cbd5e1;">{{ item.advice }}</p>
        </div>
      </div>
      <div *ngIf="item.drills?.length" style="display:flex; flex-wrap:wrap; gap:8px; margin-top:8px;">
        <span *ngFor="let drill of item.drills" class="badge" style="background: rgba(59,130,246,0.2); color:#93c5fd;">{{ drill }}</span>
      </div>
    </div>
  </div>

  <div *ngIf="analysis.all_gaps?.length" style="background: rgba(255,255,255,0.05); padding:16px; border-radius: 12px; border:1px solid rgba(255,255,255,0.12);">
    <h4 style="margin-top:0;">All Stats vs Next Rank</h4>
    <div style="display:grid; gap:12px;">
      <div *ngFor="let gap of analysis.all_gaps | slice:0:6" style="background: rgba(15,23,42,0.75); padding:12px; border-radius:12px; display:flex; justify-content:space-between; align-items:center;">
        <span>{{ formatStatName(gap.stat) }}</span>
        <span [style.color]="gap.gap > 0 ? '#fb7185' : '#34d399'">{{ gap.gap > 0 ? '↓' : '↑' }} {{ gap.gap_percentage | number:'1.0-0' }}%</span>
      </div>
    </div>
  </div>
</div>
